// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/b/index.tsx";
import * as $3 from "./routes/contact.tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/whoami.tsx";
import * as $$0 from "./islands/HamburgerMenu.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/b/index.tsx": $2,
    "./routes/contact.tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/whoami.tsx": $5,
  },
  islands: {
    "./islands/HamburgerMenu.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
